version 0.2.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#! /bin/sh
 # Anticonf (tm) script by Jeroen Ooms and Thomas Lin Pedersen(2020)
 # This script will query 'pkg-config' for the required cflags and ldflags.
 # If pkg-config is unavailable or does not find the library, try setting
@@ -15,9 +15,9 @@ PKG_TEST_HEADER="#include <hb-ft.h>"
 PKG_LIBS="-lfreetype -lharfbuzz -lfribidi"
 
 # Use pkg-config if available
-if [ $(command -v pkg-config) ]; then
-  PKGCONFIG_CFLAGS=$(pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME})
-  PKGCONFIG_LIBS=$(pkg-config --libs ${PKG_CONFIG_NAME})
+if [ "`command -v pkg-config`" ]; then
+  PKGCONFIG_CFLAGS="`pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME}`"
+  PKGCONFIG_LIBS="`pkg-config --libs ${PKG_CONFIG_NAME}`"
 fi
 
 # Note that cflags may be empty in case of success
@@ -27,16 +27,16 @@ if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
   PKG_LIBS="-L$LIB_DIR $PKG_LIBS"
 elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
   echo "Found pkg-config cflags and libs!"
-  PKG_CFLAGS=${PKGCONFIG_CFLAGS}
-  PKG_LIBS=${PKGCONFIG_LIBS}
-elif [[ "$OSTYPE" == "darwin"* ]]; then
+  PKG_CFLAGS="${PKGCONFIG_CFLAGS}"
+  PKG_LIBS="${PKGCONFIG_LIBS}"
+elif [ "`uname`" = "Darwin" ]; then
   brew --version 2>/dev/null
   if [ $? -eq 0 ]; then
-    BREWDIR=$(brew --prefix)
+    BREWDIR="`brew --prefix`"
     PKG_CFLAGS="-I$BREWDIR/include/freetype2 -I$BREWDIR/include/harfbuzz -I$BREWDIR/include/glib-2.0  -I$BREWDIR/include/fribidi"
   else
     curl -sfL "https://autobrew.github.io/scripts/harfbuzz" > autobrew
-    source autobrew
+    . autobrew
   fi
 fi
 
@@ -45,29 +45,34 @@ echo "Using PKG_CFLAGS=$PKG_CFLAGS"
 echo "Using PKG_LIBS=$PKG_LIBS"
 
 # Find compiler
-CC=$(${R_HOME}/bin/R CMD config CC)
-CFLAGS=$(${R_HOME}/bin/R CMD config CFLAGS)
-CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
+CC="`${R_HOME}/bin/R CMD config CC`"
+CFLAGS="`${R_HOME}/bin/R CMD config CFLAGS`"
+CPPFLAGS="`${R_HOME}/bin/R CMD config CPPFLAGS`"
 
 # Test configuration
 echo "$PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>configure.log
 
 # Customize the error
 if [ $? -ne 0 ]; then
-  echo "--------------------------- [ANTICONF] --------------------------------"
-  echo "Configuration failed to find the $PKG_CONFIG_NAME library. Try installing:"
-  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
-  echo " * rpm: $PKG_RPM_NAME (Fedora, EPEL)"
-  echo " * csw: $PKG_CSW_NAME (Solaris)"
-  echo " * brew: $PKG_BREW_NAME (OSX)"
-  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
-  echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
-  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
-  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-  echo "-------------------------- [ERROR MESSAGE] ---------------------------"
-  cat configure.log
-  echo "--------------------------------------------------------------------"
-  exit 1
+  if [ "`uname`" = "SunOS" ]; then
+    PKG_CFLAGS="$PKG_CFLAGS -DNO_HARFBUZZ_FRIBIDI"
+    PKG_LIBS=""
+  else
+    echo "--------------------------- [ANTICONF] --------------------------------"
+    echo "Configuration failed to find the $PKG_CONFIG_NAME library. Try installing:"
+    echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
+    echo " * rpm: $PKG_RPM_NAME (Fedora, EPEL)"
+    echo " * csw: $PKG_CSW_NAME (Solaris)"
+    echo " * brew: $PKG_BREW_NAME (OSX)"
+    echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
+    echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
+    echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
+    echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
+    echo "-------------------------- [ERROR MESSAGE] ---------------------------"
+    cat configure.log
+    echo "--------------------------------------------------------------------"
+    exit 1
+  fi
 fi
 
 # Write to Makevars
